@startuml

' https://api.python.langchain.com/en/latest/agents/langchain.agents.agent.AgentExecutor.html#langchain.agents.agent.AgentExecutor
class AgentExecutor{
    agent
    tools
    ---
    early_stopping_method
    handle_parsing_errors
    ---
    max_execution_time
    max_execution_iterations
    ---
    memory
    ---
    return_intermediate_steps
    trim_intermediate_steps
    verbose
}
  
@enduml